import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>luffy</title>
        <meta name="description" content="Generated by luffy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/luffy_santista.jpeg"
          alt="Vercel Logo"
          width={200}
          height={200}
        />

        <p className={styles.description}>
          luffy <code className={styles.code}>santista</code>
        </p>
        <button
          className={styles.button}
          onClick={() => {
            router.push("/zoro");
          }}
        >
          zoro
        </button>
      </main>
    </div>
  );
};

export default Home;
