import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

const ZoroPage: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>zoro</title>
          <meta name="description" content="Generated by zoro" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Image
            src="/zoro_vascaino.webp"
            alt="Vercel Logo"
            width={200}
            height={200}
          />

          <p className={styles.description}>
            zoro <code className={styles.code}>vascaino</code>
          </p>
          <button
            className={styles.button}
            onClick={() => {
              router.push("/luffy");
            }}
          >
            luffy
          </button>
        </main>
      </div>
    </>
  );
};

export default ZoroPage;
